### ISSUE TITLE
Issue openning the project; sdk 15063?

### ISSUE THREAD

**Issue by Scherlac** [COM8/Control-Test#1]
I get the following error while opening the project: 

> The imported project "C:\Program Files (x86)\Windows Kits\10\bin\10.0.15063.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\8.21\Microsoft.Windows.UI.Xaml.Common.targets

The guide tells to install the following sdk: [16299, 17134 and 17763](https://github.com/Microsoft/microsoft-ui-xaml/blob/master/docs/developer_guide.md#sdk)

**Comment by Scherlac** [comment]
This was an issue opening the project with wrong VS version. Sorry.  This is due to [this](https://developercommunity.visualstudio.com/content/problem/48999/open-in-visual-studio-from-web-gives-me-unknown-ve.html) issue.

**Comment by COM8** [comment]
Yes, you're kind of right it says in the [Guide](https://github.com/Microsoft/microsoft-ui-xaml/blob/master/docs/developer_guide.md#sdk) 16299, 17134 and 17763 are required, but Windows UI Library also supports the [Creators Update (15063)](https://github.com/Microsoft/microsoft-ui-xaml#version-support).
So just install the missing SDK via the VS installer. :D
